extends "res://tests/run_b3.gd"
func fresh(power:String) -> void:
	paused=false
	if is_instance_valid(scene):scene.queue_free();await frames(2)
	scene=load("res://scenes/preparation.tscn").instantiate();scene.auto_focus_pause=false;root.add_child(scene);await frames(3)
	serial+=1;scene.save_store.directory=base.path_join("case-%d"%serial)
	await command("please try blast, then preview shield, then show me dash")
	await command("I'd like to choose "+power)
	check("actual power selected",scene.power==power and scene.phase=="player")
func run() -> void:
	base=OS.get_environment("B4_SAVE_DIR")
	for chosen in ["blast","shield","dash"]:
		await fresh(chosen)
		await command("go to package then interact package");await fight()
		await command("go to package then collect package then go to shelter then go to desk then choose security")
		await command("go to traveler then "+("decline traveler" if chosen=="shield" else "join traveler"))
		if chosen=="dash":await command("have traveler wait here")
		await command("go to hub then go to bench then inspect bench")
		check("main route no optional work",scene.tasks.values().all(func(v):return v=="available"))
		await command("claim preparation kit")
		check("explicit kit grants exactly 20 and 3 base items",scene.progression.material==20 and scene.progression.levels=={"lens":0,"weave":0,"rig":0})
		await command("claim kit");check("repeat kit unchanged",scene.progression.material==20)
		var before:=state()
		for q in ["What equipment do I have?","Compare these.","How much material do I have?","Where can I get more?","What can I afford?","What would upgrading this change?"]:
			await command(q);check("question comparison no mutation: "+q,state()==before)
		check("ambiguous improvement clarifies",not scene.submit("improve equipment") and scene.clarification.size()==3)
		await command("inspect focus lens")
		await command("what would upgrading this change?")
		check("specific effect advice",scene.history.any(func(v):return "improved adds 2" in v))
		before=state();check("mixed improvement clarification no spend",not scene.submit("improve lens or "+chosen) and state()==before)
		await command("improve my power");check("unearned upgrade refused",scene.progression.power_level==0 and scene.progression.material==20)
		await command("go to approach then go to range then test power")
		check("base chosen power executed and earned calibration",scene.progression.calibrated and scene.practice_result.kind==chosen)
		if chosen=="blast":check("base blast actual impact",scene.practice_result.impact==3 and scene.practice_result.remaining==2)
		if chosen=="shield":check("base shield actual pressure",scene.practice_result.protection==2 and scene.practice_result.pressure==2)
		if chosen=="dash":check("base dash actual placement",scene.player_cell==Vector2i(4,0) and scene.practice_result.distance==2)
		await command("go to hub then go to bench then improve my "+chosen)
		check("power costs exactly four",scene.progression.material==16 and scene.progression.power_level==1)
		await command("improve my "+chosen);check("no second power charge",scene.progression.material==16)
		await command("improve my "+("shield" if chosen!="shield" else "dash"));check("unchosen power rejected",scene.progression.material==16)
		await command("go to approach then go to range then test power")
		if chosen=="blast":check("improved blast folds target",scene.practice_result.impact==5 and scene.practice_result.success)
		if chosen=="shield":check("improved shield blocks pulse",scene.practice_result.protection==4 and scene.practice_result.success)
		if chosen=="dash":check("improved dash actual placement",scene.player_cell==Vector2i(5,0) and scene.practice_result.distance==3)
		var paid:=0
		for id in ["lens","weave","rig"]:
			await command("equip "+scene.Rules.ITEMS[id])
			await command("go to range then "+("test bolt" if id=="lens" else "test guard" if id=="weave" else "test power"))
			if id=="lens":check("base lens impact",scene.practice_result.impact==3)
			if id=="weave":check("base weave protection",scene.practice_result.protection==1)
			if id=="rig" and chosen=="dash":check("base rig physical distance",scene.player_cell==Vector2i(6,0))
			await command("go to hub then go to bench then improve "+id);paid+=4
			check("independent exact gear cost "+id,scene.progression.material==16-paid and scene.progression.levels[id]==1)
			await command("improve "+id);check("repeat tier costs nothing",scene.progression.material==16-paid)
			await command("go to approach then go to range then "+("test bolt" if id=="lens" else "test guard" if id=="weave" else "test power"))
			if id=="lens":check("improved lens impact",scene.practice_result.impact==4)
			if id=="weave":check("improved weave protection",scene.practice_result.protection==2)
			if id=="rig" and chosen=="dash":check("improved rig physical distance",scene.player_cell==Vector2i(7,0))
			await command("unequip that")
			check("unequip retains ownership removes bonuses",scene.progression.equipped=="" and scene.effects().bolt==2 and scene.effects().guard==0)
		check("all required progression affordable without tasks",scene.progression.material==4 and scene.tasks.values().all(func(v):return v=="available"))
		await command("equip "+{"blast":"lens","shield":"weave","dash":"rig"}[chosen])
		await command("go to range then test power")
		check("maximum chosen effect",scene.practice_result.get("impact",scene.practice_result.get("protection",scene.practice_result.get("distance",0)))=={"blast":7,"shield":6,"dash":5}[chosen])
		before=scene.progression.duplicate(true)
		await command("equip "+scene.progression.equipped)
		await command("go to range then test power")
		check("repeat equip practice no compounded stats or farming",scene.progression==before)
		await optional_route(chosen)
		await command("go to hub then go to shelter then go to desk then rest")
		check("rest free and actual health",scene.hp==6 and scene.progression.material==8)
		if chosen=="dash":
			check("waiting party preserved",scene.recruit_status=="waiting")
			await command("go to traveler then rejoin traveler")
		if chosen=="shield":
			check("declined party preserved",scene.recruit_status=="declined")
			await command("go to traveler then join traveler")
		await command("go to hub then go to approach then go to range")
		await frames(180);await command("save")
		var saved:Dictionary=scene.save_store.latest()
		check("full B4 schema valid",scene.save_store.valid(saved))
		await command("continue")
		check("reload exact progression inactive history",scene.progression==saved.progression and scene.tasks==saved.tasks and scene.work.is_empty() and scene.current.is_empty())
		restarts.append({"directory":scene.save_store.directory,"expected":scene.save_store.latest()})
	await failures_and_controls()
	restarts[-1].expected=scene.save_store.latest()
	var f:=FileAccess.open(base.path_join("restarts.json"),FileAccess.WRITE);f.store_string(JSON.stringify(restarts));f.close()
	f=FileAccess.open(OS.get_environment("B4_CHECKS_PATH"),FileAccess.WRITE);f.store_string(JSON.stringify(checks,"  "));f.close()
	quit(0 if checks.all(func(c):return c.passed) else 1)
func optional_route(chosen:String) -> void:
	await command("go to hub")
	if chosen=="blast":await command("ask pet to fetch supplies")
	else:await command("go to supplies then collect supplies")
	check("bundle itself is not currency",scene.progression.material==4 and scene.held_bundles()==1)
	var method:String=scene.supply_method
	await command("go to bench then exchange the supply bundle")
	check("one explicit conversion +4 with preserved consequence",scene.progression.material==8 and scene.held_bundles()==0 and scene.supply_method==method and scene.tasks.supplies=="completed")
	await command("exchange supply bundle");check("redemption cannot repeat",scene.progression.material==8)
	await command("go to access then restore access panel then go to approach then go to marker then survey the approach")
	check("shortcut and survey no silent currency",scene.progression.material==8 and scene.tasks.access=="completed" and scene.tasks.survey=="completed")
func failures_and_controls() -> void:
	await controls()
	await command("go to hub then go to bench")
	var saved:Dictionary=scene.save_store.latest()
	var original:String=scene.save_store.directory
	# Explicit synthetic fresh-kit branch for rejected/failing transactions, not a played reward.
	var fixture:Dictionary=scene.snapshot();fixture.progression={"material":20,"kit_claimed":true,"bundle_exchanged":false,"levels":{"lens":0,"weave":0,"rig":0},"equipped":"lens","power_level":0,"calibrated":true}
	fixture.version=1;fixture.sequence=1;fixture.kind="manual"
	check("transaction fixture independently valid",scene.save_store.valid(fixture));scene.apply_snapshot(fixture)
	var obstruction:=base.path_join("b4-save-obstruction")
	var f:=FileAccess.open(obstruction,FileAccess.WRITE);f.store_string("synthetic");f.close()
	scene.save_store.directory=obstruction.path_join("saves")
	var before:=state()
	await command("improve lens")
	check("failed purchase restores balance tier and truthful error",state()==before and "unchanged" in scene.message)
	await command("exchange bundle");check("failed conversion restores bundle and material",state()==before and scene.held_bundles()==1)
	await command("equip weave");check("failed equip preserves previous loadout",state()==before)
	await command("improve my power");check("failed power purchase coherent",state()==before)
	var unclaimed:Dictionary=fixture.duplicate(true);unclaimed.progression=scene.Rules.initial();scene.apply_snapshot(unclaimed)
	before=state();await command("claim kit");check("failed acquisition grants nothing",state()==before)
	scene.apply_snapshot(fixture)
	var range_fixture:Dictionary=fixture.duplicate(true);range_fixture.location="approach";range_fixture.player=[2,0];range_fixture.pet_position=[320,254];range_fixture.recruit_position=[384,318];range_fixture.progression.calibrated=false
	scene.apply_snapshot(range_fixture);before=state();await command("test power")
	check("failed calibration or dash save rolls back placement and earning",state()==before and not scene.progression.calibrated)
	scene.apply_snapshot(fixture)
	check("failed quit stays open",not scene.save_and_quit() and not scene.quit_requested)
	scene.save_store.directory=original
	# Deliberately invalid low-balance injection tests the guard, never saved or accepted as compatibility.
	scene.progression.material=3
	await command("improve lens");check("insufficient funds no upgrade or deduction",scene.progression.material==3 and scene.progression.levels.lens==0)
	scene.progression.material=20
	check("stale purchase rejected",not scene.submit("improve lens","old-purchase",scene.epoch-1))
	check("fresh purchase accepted",scene.submit("improve lens","purchase-once",scene.epoch));await settle()
	check("duplicate purchase rejected",not scene.submit("improve weave","purchase-once",scene.epoch) and scene.progression.material==16 and scene.progression.levels.weave==0)
	var stable:Dictionary=scene.save_store.latest()
	for field in ["progression_version","progression"]:
		var bad:Dictionary=stable.duplicate(true);bad.erase(field);check("missing B4 field rejected "+field,not scene.save_store.valid(bad))
	for field in ["material","power_level","equipped","levels","bundle_exchanged"]:
		var bad:Dictionary=stable.duplicate(true)
		bad.progression[field]={"material":999,"power_level":2,"equipped":"unknown","levels":{"lens":1},"bundle_exchanged":true}[field]
		check("inconsistent progression rejected "+field,not scene.save_store.valid(bad))
	scene.submit("go to approach then test power");await frames(8);paused=true
	var pos:Vector2=scene.human.position;await frames(30);check("pause freezes preparation travel",scene.human.position==pos)
	scene.submit("Stop");paused=false;await settle();check("Stop cancels pending practice",scene.location=="hub")
	# Ordinary defeat's actual retry motion calls the same latest-save authority.
	scene.progression.material=0;scene.phase="defeat";scene.animate("retry",0.1,scene.human.position,scene.human.position);await frames(20)
	check("ordinary retry restores paid state without new grants",scene.progression==stable.progression and scene.phase==stable.phase)
	scene.apply_snapshot(saved);await command("go to approach then save")
	await world_recovery()
