extends "res://tests/run_b25.gd"
func fresh(power:String) -> void:
	paused=false
	if is_instance_valid(scene):scene.queue_free();await frames(2)
	scene=load("res://scenes/connected_world.tscn").instantiate();scene.auto_focus_pause=false;root.add_child(scene);await frames(3)
	serial+=1;scene.save_store.directory=base.path_join("case-%d"%serial)
	await command("please try blast, then preview shield, then show me dash")
	await command("I'd like to choose "+power)
	check("actual power selected",scene.power==power and scene.phase=="player")
func settle() -> void:
	for i in range(9000):
		if not scene.busy and scene.work.is_empty() and scene.current.is_empty() and scene.fetch_state.is_empty() and scene.supply_trip.is_empty():return
		await process_frame
	check("bounded B3 completion",false);scene.stop_work("Test timeout")
func opening(branch:String) -> void:
	await fresh("blast")
	await command("go to package then interact package")
	await fight();await command("go to package then collect package")
	await command("go to shelter then inspect desk")
	check("new room clause resolves after travel",scene.location=="shelter" and scene.recent=="desk")
	await command("go to desk then choose equipment")
	await command("go to traveler then "+("decline traveler" if branch=="declined" else "join traveler"))
	if branch=="waiting":await command("have traveler wait here")
	await command("go to concourse")
	await command("go to cache then collect cache")
	await command("go to shelter then go to hub then inspect board")
	check("connected ordinary route with saved earlier consequence",scene.location=="hub" and scene.cache_taken and scene.retrieval=="personal" and scene.enemy_hp==0)
	check("party branch at hub: "+branch,scene.recruit_status==branch and scene.recruit.visible==(branch=="joined"))
func run() -> void:
	base=OS.get_environment("B3_SAVE_DIR")
	for branch in ["joined","declined","waiting"]:
		await opening(branch)
		var before:=state()
		await command("what work is unfinished?")
		check("question-only state unchanged",state()==before)
		check("home blocked",not scene.submit("go to home"))
		check("nonadjacent destination blocked",not scene.submit("go to concourse"))
		check("invalid direct transition blocked",not scene.travel("approach"))
		check("ambiguous doors clarified",not scene.submit("go to doorway") and scene.clarification.size()==2)
		await command("inspect access panel")
		await command("skip access");await command("decline supplies")
		check("skipped statuses saved",scene.tasks.access=="skipped" and scene.tasks.supplies=="skipped")
		await command("go to approach then inspect marker")
		check("optional skipping leaves route viable",scene.location=="approach" and scene.recent=="survey")
		await command("skip survey");await command("survey the approach")
		check("skipped survey does not complete",scene.tasks.survey=="skipped")
		await command("resume survey then go to marker then survey the approach")
		check("survey actual discovery",scene.tasks.survey=="completed" and "drainage" in scene.survey_description())
		await command("go to hub then inspect it")
		check("cross-room pronoun invalidated",scene.location=="hub" and scene.recent=="" and scene.history.any(func(s):return "After completed actions" in s))
		await command("resume access then go to access then restore access panel")
		check("access opens actual floor",scene.tasks.access=="completed" and scene.floor_free(Vector2i(5,3)))
		await command("resume supplies")
		if branch=="joined":
			var position:Vector2i=scene.player_cell
			scene.submit("ask pet to fetch supplies");await frames(35)
			check("active supply task blocks saving",not scene.stable_boundary() and not scene.manual_save())
			paused=true;var at:Vector2=scene.pet.position;await frames(20)
			check("pause freezes physical trip",scene.pet.position==at)
			scene.submit("stop");paused=false;await settle()
			check("Stop cancels task without reward",scene.tasks.supplies=="available" and scene.supply_method=="")
			await command("inspect supplies then ask pet to fetch it")
			check("pet round trip leaves protagonist in place",scene.player_cell==position and scene.supply_method=="pet")
		else:
			await command("go to supplies then recover supplies")
			check("personal approach requires walking",scene.distance(scene.player_cell,Vector2i(8,4))<=1 and scene.supply_method=="personal")
		check("one supply bundle",scene.tasks.supplies=="completed")
		var method:String=scene.supply_method
		await command("go to supplies then collect supplies")
		check("repeat gain refused",scene.supply_method==method and scene.tasks.supplies=="completed")
		await command("go to approach then go to hub then go to shelter")
		check("all new doors both directions",scene.location=="shelter")
		if branch=="waiting":
			check("waiting recruit remains in shelter",scene.recruit.visible and scene.recruit_status=="waiting")
			await command("go to traveler then rejoin traveler")
			check("waiting can rejoin",scene.recruit_status=="joined")
		if branch=="declined":
			await command("go to traveler then join traveler")
			check("declined can join",scene.recruit_status=="joined")
		await command("go to hub then go to approach")
		await frames(200);await command("save")
		var saved:Dictionary=scene.save_store.latest()
		check("B3 schema validates",scene.save_store.valid(saved))
		restarts.append({"directory":scene.save_store.directory,"expected":saved})
		await command("continue")
		check("reload retains tasks method and inactive commands",scene.tasks==saved.tasks and scene.supply_method==saved.supply_method and scene.work.is_empty() and scene.current.is_empty())
	await rollback_checks()
	await controls()
	await world_recovery()
	restarts[-1].expected=scene.save_store.latest() # Recovery intentionally writes newer snapshots.
	var f:=FileAccess.open(base.path_join("restarts.json"),FileAccess.WRITE);f.store_string(JSON.stringify(restarts));f.close()
	f=FileAccess.open(OS.get_environment("B3_CHECKS_PATH"),FileAccess.WRITE);f.store_string(JSON.stringify(checks,"  "));f.close()
	quit(0 if checks.all(func(c):return c.passed) else 1)
func controls() -> void:
	await command("go to hub then go to shelter then go to hub")
	await command("move 2 right and 2 up")
	check("exact movement sequence",scene.steps_done==4 and scene.player_cell==Vector2i(3,3))
	var before:=state()
	scene.command_input.grab_focus();await key(KEY_W);await key(KEY_A);await key(KEY_S);await key(KEY_D);await key(KEY_E)
	check("B3 text focus captures shortcuts",state()==before)
	scene.command_input.clear();scene.command_input.release_focus()
	scene.submit("go to approach");await frames(8);scene.submit("actually, inspect board");await settle()
	check("correction cancels future travel",scene.location=="hub" and scene.recent=="board")
	scene.submit("go to approach");await frames(8);await key(KEY_S);await settle()
	check("direct reclaim cancels travel",scene.location=="hub" and scene.work.is_empty())
	before=state();scene.submit("inspect board","once",scene.epoch);await settle()
	check("duplicate rejected",not scene.submit("go to approach","once",scene.epoch) and state()==before)
	check("stale rejected",not scene.submit("go to approach","stale",scene.epoch-1))
	await command("go to approach then dance around the moon")
	check("unsupported continuation truthfully stops after travel",scene.location=="approach" and scene.work.is_empty())
	check("character feed boundary", "cannot" in scene.question("what can the audience tell me?"))
func world_recovery() -> void:
	await command("save")
	var valid:Dictionary=scene.save_store.latest()
	for field in ["world_version","tasks","supply_method","adventure_version"]:
		var bad:Dictionary=valid.duplicate(true);bad.erase(field);check("missing field rejected "+field,not scene.save_store.valid(bad))
	var bad:Dictionary=valid.duplicate(true);bad.tasks.supplies="active";check("unfinished task cannot be restored",not scene.save_store.valid(bad))
	bad=valid.duplicate(true);bad.supply_method="";check("inconsistent reward method rejected",not scene.save_store.valid(bad))
	bad=valid.duplicate(true);bad.location="owned_home";check("future location rejected",not scene.save_store.valid(bad))
	bad=valid.duplicate(true);bad.player=[9,1];check("blocked placement rejected",not scene.save_store.valid(bad))
	var original:String=scene.save_store.directory
	var obstruction:=base.path_join("file-not-folder")
	var file:=FileAccess.open(obstruction,FileAccess.WRITE);file.store_string("synthetic obstruction");file.close()
	scene.save_store.directory=obstruction.path_join("saves")
	var before:=state()
	check("failed Save and quit stays open",not scene.save_and_quit() and not scene.quit_requested and state()==before)
	scene.save_store.directory=original
	check("save retry succeeds",scene.manual_save())
	file=FileAccess.open(original.path_join("snapshot-000900001.json"),FileAccess.WRITE);file.store_string("{invalid");file.close()
	file=FileAccess.open(original.path_join("snapshot-000900002.tmp"),FileAccess.WRITE);file.store_string("partial");file.close()
	check("invalid partial recovery",scene.load_latest() and "Skipped 2" in scene.save_store.notice)
	check("invalid material retained",FileAccess.file_exists(original.path_join("snapshot-000900001.json")))
	DirAccess.make_dir_absolute(original.path_join(".writing"))
	file=FileAccess.open(original.path_join(".writing/owner.json"),FileAccess.WRITE);file.store_string(JSON.stringify({"pid":OS.get_process_id()}));file.close()
	check("active writer protected",not scene.recover_save_access() and not scene.manual_save())
	file=FileAccess.open(original.path_join(".writing/owner.json"),FileAccess.WRITE);file.store_string(JSON.stringify({"pid":2147483646}));file.close()
	check("interrupted writer preserved recovery",scene.recover_save_access() and scene.manual_save())

func rollback_checks() -> void:
	# Explicit synthetic unfinished-task fixture derived from a valid journey.
	var original:String=scene.save_store.directory
	var saved:Dictionary=scene.save_store.latest()
	var fixture:Dictionary=saved.duplicate(true)
	fixture.location="hub";fixture.player=[4,2];fixture.pet_position=[512,446];fixture.recruit_position=[512,318]
	fixture.tasks={"supplies":"available","access":"available","survey":"available"};fixture.supply_method=""
	check("rollback fixture valid",scene.save_store.valid(fixture))
	scene.apply_snapshot(fixture)
	var closed_path:int=scene.path_to(Vector2i(6,3)).size()
	var obstruction:=base.path_join("task-obstruction")
	var f:=FileAccess.open(obstruction,FileAccess.WRITE);f.store_string("synthetic");f.close()
	scene.save_store.directory=obstruction.path_join("saves")
	check("failed task write rolls back geometry and status",not scene.task_action("access","restore") and scene.tasks.access=="available" and not scene.floor_free(Vector2i(5,3)))
	scene.save_store.directory=original
	check("task retry succeeds",scene.task_action("access","restore"))
	check("shortcut measurably shortens route",scene.path_to(Vector2i(6,3)).size()<closed_path)
	await command("move down and 2 right")
	check("protagonist traverses opened shortcut",scene.player_cell==Vector2i(6,3))
	await command("go to shelter")
	await command("go to hub")
	scene.save_store.directory=obstruction.path_join("saves")
	var before:=state()
	check("failed travel rolls back whole state",not scene.travel("shelter") and state()==before)
	scene.save_store.directory=original
	scene.apply_snapshot(saved)
