extends "res://tests/run_b7.gd"
var capture_dir:=""
func check(label:String,value:bool) -> void:
	super.check(label,value)
	if not value:push_error(label);quit(1)
func command(text:String) -> void:
	scene.command_input.text=text;await frames(18)
	scene.command_input.text_submitted.emit(text);await frames(2);await settle();await frames(25)
func shot(label:String) -> void:
	await frames(75);await RenderingServer.frame_post_draw
	root.get_texture().get_image().save_png(capture_dir.path_join(label+".png"))
	print("TOUR_PHASE ",label," ",JSON.stringify(scene.snapshot()))
func run() -> void:
	base=OS.get_environment("B7_SAVE_DIR");capture_dir=OS.get_environment("B7_CAPTURE_DIR")
	await opening("joined");await shot("01-ordinary-opening")
	await command("go to bench then claim preparation kit then equip guard weave")
	await command("ask pet to fetch supplies then go to bench then exchange supply bundle")
	await command("go to access then restore access then go to board then file settlement claim then go home")
	await command("buy chair then place chair by the window then buy lamp then place lamp by the alcove then buy shelf then place shelf by the far wall")
	await command("go to locker then improve storage then deposit 4 material");await shot("02-private-preparation")
	await command("go to hub then go to approach then go to marker then survey the approach")
	await command("go to range then test power then teach pet cover fetch")
	await command("go to hub then go to bench then improve lens then improve my power")
	await command("go to shelter then go to desk then rest then go to hub then go to approach")
	await command("what am I preparing for?");await shot("03-assignment")
	await command("enter expedition");await shot("04-west-court")
	await command("end turn");check("movie learned cover and injury",scene.expedition.cover and scene.care.pet=="injured");await shot("05-cover-and-support")
	await command("guard then end turn");check("movie recruit downed",scene.care.recruit=="downed");await shot("06-recoverable-setback")
	await command("retreat then go to hub then go to shelter then go to desk")
	await command("treat the pet then help the companion recover then rest");await shot("07-explicit-care")
	await command("go to hub then go to bench then equip lens then go to approach then enter expedition")
	check("movie persistent progress",scene.expedition.warden==10)
	await command("move right then use blast");await command("end turn");await command("shoot creature");check("movie yard resolved",scene.expedition.cleared);await shot("08-preparation-effects")
	await command("what do we know about the route?");await command("take the drainage route");await shot("09-survey-alternative")
	await yard_walk("drainage");await yard_walk("core");await shot("10-crossed-dry-passage")
	await command("recover routing core");check("movie objective actual",scene.expedition.objective and scene.progression.material==8);await shot("11-objective")
	await command("retreat then go to hub then go to board then file relay report")
	check("movie full chapter reward exactly once",scene.expedition.reported and scene.progression.material==16)
	await command("what did we accomplish?");await shot("12-chapter-resolution")
	await command("go home");await shot("13-home-with-consequences")
	await frames(120);await command("save")
	var expected:Dictionary=scene.save_store.latest()
	var f:=FileAccess.open(base.path_join("restarts.json"),FileAccess.WRITE);f.store_string(JSON.stringify([{"directory":scene.save_store.directory,"expected":expected}]));f.close()
	print("TOUR_FINAL ",JSON.stringify(expected));check("tour actual save and quit",scene.save_and_quit())
